services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    container_name: travel-chatbot-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
    - MLFLOW_MONITORING_PATH=/app/monitoring
    volumes:
      - ./backend/data:/app/backend/data
      - ./monitoring:/app/monitoring
     
    command: >
      uv run uvicorn backend.app.main:app
      --host 0.0.0.0
      --port 8000

    
    frontend:
      build:
        context: .
        dockerfile: dockerfiles/frontend.dockerfile
      container_name: travel-chatbot-frontend
      ports:
        - "8501.8501"
      env_file:
        - .env
      environment:
        - BACKEND_URL=http://backend:8000
      depends_on:
        - backend
      
      mlflow:
        build:
          context: .
          dockerfile: dockerfiles/backend.dockerfile
        container_name: travel-chatbot-mlflow
        ports:
          - "5000:5000"
        volumes:
          - ./monitoring:/app/monitoring
        command: >
          uv run mlflow ui
          --backend-store-uri sqlite:///app/monitoring/mlflow.db
          --host 0.0.0.0
          --port 5001
